const map=L.map('map',{zoomControl:false,tap:true}).setView([51.76,19.46],11);
map.createPane('safeAreaPane');map.getPane('safeAreaPane').style.zIndex='410';map.getPane('safeAreaPane').style.pointerEvents='none';map.createPane('safetyPane');map.getPane('safetyPane').style.zIndex='450';map.getPane('safetyPane').style.pointerEvents='none';L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
let me,accuracyCircle,safetyCircle,safetyLine=null,features=[],manualFeatures=[],deletedIds=new Set(),watchId=null,lastPos=null,lastBest=Infinity,lastNearestPoint=null,editMode=null,loading=false,undoStack=[];const safeAreaLayer=L.layerGroup().addTo(map);
const buildingsLayer=L.geoJSON(null,{style:{weight:2,color:'#8f3b36',fillColor:'#a95750',fillOpacity:.20,className:'safe-building'}}).addTo(map);
const manualLayer=L.layerGroup().addTo(map);
const distEl=document.querySelector('#distance'),statusEl=document.querySelector('#status'),accEl=document.querySelector('#accuracy'),panel=document.querySelector('#panel'),safeInput=document.querySelector('#safeDistance'),editHint=document.querySelector('#editHint');
const saved=localStorage.getItem('safeDistance');if(saved)safeInput.value=saved;const refreshDaysInput=document.querySelector('#refreshDays');const savedRefreshDays=localStorage.getItem('safeHuntRefreshDays');if(savedRefreshDays)refreshDaysInput.value=savedRefreshDays;
function rad(x){return x*Math.PI/180} function hav(a,b){const R=6371000,dLat=rad(b[0]-a[0]),dLon=rad(b[1]-a[1]),x=Math.sin(dLat/2)**2+Math.cos(rad(a[0]))*Math.cos(rad(b[0]))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function segNearest(p,a,b){const lat0=rad(p[0]),mx=111320*Math.cos(lat0),my=110540;let px=p[1]*mx,py=p[0]*my,ax=a[1]*mx,ay=a[0]*my,bx=b[1]*mx,by=b[0]*my,dx=bx-ax,dy=by-ay,t=((px-ax)*dx+(py-ay)*dy)/(dx*dx+dy*dy||1);t=Math.max(0,Math.min(1,t));const qx=ax+t*dx,qy=ay+t*dy;return{distance:Math.hypot(px-qx,py-qy),point:[qy/my,qx/mx]}}
function ringNearest(p,ring){let best={distance:Infinity,point:null};for(let i=1;i<ring.length;i++){const r=segNearest(p,[ring[i-1][1],ring[i-1][0]],[ring[i][1],ring[i][0]]);if(r.distance<best.distance)best=r}return best}
function geomNearest(p,g){if(g.type==='Point')return{distance:hav(p,[g.coordinates[1],g.coordinates[0]]),point:[g.coordinates[1],g.coordinates[0]]};let best={distance:Infinity,point:null};const rings=g.type==='Polygon'?g.coordinates:g.type==='MultiPolygon'?g.coordinates.flat():[];for(const ring of rings){const r=ringNearest(p,ring);if(r.distance<best.distance)best=r}return best}
function allFeatures(){return features.filter(f=>!deletedIds.has(String(f.properties?.osmId))).concat(manualFeatures)}
function pushUndo(action){undoStack.push(action);if(undoStack.length>30)undoStack.shift();document.querySelector('#undoEdit').disabled=false}
function undoLast(){const a=undoStack.pop();if(!a)return;if(a.type==='addManual')manualFeatures=manualFeatures.filter(f=>f!==a.feature);else if(a.type==='removeManual')manualFeatures.splice(Math.max(0,a.index),0,a.feature);else if(a.type==='deleteOsm')deletedIds.delete(a.id);saveEdits();redraw();document.querySelector('#undoEdit').disabled=undoStack.length===0;statusEl.textContent='Cofnięto ostatnią zmianę budynków.'}
function renderSafeDistanceZone(){safeAreaLayer.clearLayers();const fs=allFeatures();if(!fs.length)return;const limit=Math.max(1,Number(safeInput.value)||150),size=map.getSize(),step=48;for(let x=24;x<size.x;x+=step){for(let y=24;y<size.y;y+=step){const ll=map.containerPointToLatLng([x,y]);let best=Infinity;for(const f of fs){const r=geomNearest([ll.lat,ll.lng],f.geometry);if(r.distance<best)best=r.distance;if(best<limit)break}if(best>=limit)L.circleMarker(ll,{pane:'safeAreaPane',radius:13,stroke:false,fillColor:'#19a94b',fillOpacity:.16,interactive:false,className:'safe-distance-zone'}).addTo(safeAreaLayer)}}}
function redraw(){const visible=features.filter(f=>!deletedIds.has(String(f.properties?.osmId)));buildingsLayer.clearLayers();for(const f of visible){const layer=L.geoJSON(f,{style:{weight:2,color:'#8f3b36',fillColor:'#a95750',fillOpacity:.20,className:'safe-building'}}).getLayers()[0];if(!layer)continue;layer.on('click',e=>{if(editMode!=='remove')return;L.DomEvent.stopPropagation(e);const id=String(f.properties?.osmId);deletedIds.add(id);pushUndo({type:'deleteOsm',id});saveEdits();redraw();setEdit(null);statusEl.textContent='Budynek ukryty. Możesz cofnąć zmianę.'});buildingsLayer.addLayer(layer)}manualLayer.clearLayers();for(const f of manualFeatures){const [lon,lat]=f.geometry.coordinates;const m=L.marker([lat,lon],{icon:L.divIcon({className:'',html:'<div class="manual-building" style="width:18px;height:18px"></div>',iconSize:[18,18],iconAnchor:[9,9]})}).addTo(manualLayer);m.on('click',e=>{if(editMode!=='remove')return;L.DomEvent.stopPropagation(e);const idx=manualFeatures.indexOf(f);manualFeatures=manualFeatures.filter(x=>x!==f);pushUndo({type:'removeManual',feature:f,index:idx});saveEdits();redraw();setEdit(null);statusEl.textContent='Ręcznie dodany budynek usunięty. Możesz cofnąć zmianę.'})}if(lastPos)updateNearest(...lastPos);renderSafeDistanceZone()}
function updateSafetyVisual(){if(!lastPos)return;const r=Math.max(1,Number(safeInput.value)||150);if(!safetyCircle)safetyCircle=L.circle(lastPos,{pane:'safetyPane',radius:r,weight:4,color:'#16883b',opacity:1,fillColor:'#39b95a',fillOpacity:.22,className:'safe-radius',interactive:false}).addTo(map);else safetyCircle.setLatLng(lastPos).setRadius(r);safetyCircle.bringToFront()}
function fitSafety(){if(!lastPos){statusEl.textContent='Najpierw uruchom GPS.';return}updateSafetyVisual();const bounds=safetyCircle.getBounds();const z=Math.min(18,map.getBoundsZoom(bounds,false,[70,70]));map.setView(lastPos,z,{animate:true})}
safeInput.onchange=()=>{let v=Math.max(1,Math.min(5000,Number(safeInput.value)||150));safeInput.value=v;localStorage.setItem('safeDistance',v);updateSafetyVisual();applyWarning(lastBest);renderSafeDistanceZone();fitSafety()};
function updateSafetyLine(p,best,nearest){const limit=Number(safeInput.value||150),show=Number.isFinite(best)&&best<limit&&nearest;if(show){if(!safetyLine)safetyLine=L.polyline([p,nearest],{weight:4,dashArray:'10 8',opacity:.9,interactive:false}).addTo(map);else safetyLine.setLatLngs([p,nearest]);}else if(safetyLine){map.removeLayer(safetyLine);safetyLine=null}}
function applyWarning(best){lastBest=best;panel.classList.toggle('warn',Number.isFinite(best)&&best<Number(safeInput.value||150));if(lastPos)updateSafetyLine(lastPos,lastBest,lastNearestPoint)}
function updateNearest(lat,lon){const fs=allFeatures();if(!fs.length){distEl.textContent='— m';lastNearestPoint=null;updateSafetyLine([lat,lon],Infinity,null);return}let best=Infinity,nearest=null;for(const f of fs){const r=geomNearest([lat,lon],f.geometry);if(r.distance<best){best=r.distance;nearest=r.point}}lastNearestPoint=nearest;distEl.textContent=Math.round(best)+' m';statusEl.textContent=best<Number(safeInput.value)?'UWAGA — poniżej ustawionej odległości':'Odległość do najbliższego obrysu budynku';applyWarning(best)}
// IndexedDB: wiele zapisanych obszarów 1500 m, każdy ważny 30 dni. Dzięki temu ruch nie usuwa wcześniej pobranych danych.
const DB='safe-hunt-data',STORE='areas';function refreshAgeMs(){const d=Math.max(1,Math.min(365,Number(refreshDaysInput?.value)||30));return d*24*60*60*1000}function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function dbAll(){try{const db=await openDB();return await new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}catch(_){return[]}}async function dbPut(v){try{const db=await openDB();await new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(v);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}catch(_){}}
function loadEdits(){try{manualFeatures=JSON.parse(localStorage.getItem('safeHuntManual')||'[]');deletedIds=new Set(JSON.parse(localStorage.getItem('safeHuntDeleted')||'[]'))}catch(_){manualFeatures=[];deletedIds=new Set()}}function saveEdits(){localStorage.setItem('safeHuntManual',JSON.stringify(manualFeatures));localStorage.setItem('safeHuntDeleted',JSON.stringify([...deletedIds]))}
async function restoreAreas(lat,lon){const areas=await dbAll(),near=areas.filter(a=>hav([lat,lon],[a.lat,a.lon])<=1500);const byId=new Map();for(const a of near)for(const f of a.features||[])byId.set(String(f.properties?.osmId||Math.random()),f);features=[...byId.values()];redraw();const fresh=near.some(a=>Date.now()-a.at<refreshAgeMs()&&hav([lat,lon],[a.lat,a.lon])<900);return{has:features.length>0,fresh}}
const overpassServers=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter','https://overpass.private.coffee/api/interpreter'];async function fetchWithTimeout(url,q,ms=14000){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),ms);try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:'data='+encodeURIComponent(q),signal:ctrl.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(timer)}}
async function loadBuildings(lat,lon,force=false){if(loading&&!force)return;const cache=await restoreAreas(lat,lon);if(cache.has)statusEl.textContent=cache.fresh?'Budynki z pamięci offline':'Budynki z pamięci — wymagają odświeżenia';if(cache.fresh&&!force){updateNearest(lat,lon);return}if(!navigator.onLine){statusEl.textContent=cache.has?'Tryb offline — używam zapisanych budynków':'Brak internetu i brak zapisanych budynków w tym obszarze';return}loading=true;const q=`[out:json][timeout:20];way["building"](around:1500,${lat},${lon});out geom;`;let err='';for(let i=0;i<overpassServers.length;i++){try{statusEl.textContent=`Pobieram budynki… ${i+1}/${overpassServers.length}`;const data=await fetchWithTimeout(overpassServers[i],q);const fresh=data.elements.filter(e=>e.type==='way'&&e.geometry?.length>2).map(e=>({type:'Feature',properties:{osmId:e.id},geometry:{type:'Polygon',coordinates:[e.geometry.map(x=>[x.lon,x.lat])]}}));if(!fresh.length)throw new Error('Brak danych');await dbPut({id:`${lat.toFixed(4)},${lon.toFixed(4)}`,lat,lon,at:Date.now(),features:fresh});await restoreAreas(lat,lon);statusEl.textContent='Budynki zapisane offline na '+Math.max(1,Math.min(365,Number(refreshDaysInput?.value)||30))+' dni';loading=false;return}catch(e){err=e.name==='AbortError'?'timeout':e.message}}loading=false;statusEl.textContent=cache.has?'Sieć niedostępna — pozostaję przy danych offline':'Nie udało się pobrać budynków ('+err+')'}
const hunterIcon=L.divIcon({className:'hunter-icon',html:'<div class="hunter-badge">🧑‍🌾</div>',iconSize:[48,48],iconAnchor:[24,24]});let firstFix=true;async function onPos(pos){const {latitude:lat,longitude:lon,accuracy}=pos.coords;lastPos=[lat,lon];accEl.textContent='Dokładność GPS: ±'+Math.round(accuracy)+' m';if(!me){me=L.marker(lastPos,{icon:hunterIcon}).addTo(map);accuracyCircle=L.circle(lastPos,{radius:accuracy,weight:1,fillOpacity:.06}).addTo(map)}else{me.setLatLng(lastPos);accuracyCircle.setLatLng(lastPos).setRadius(accuracy)}updateSafetyVisual();if(firstFix){fitSafety();firstFix=false}updateSolar(lat,lon);updateGameInfo();updateNearest(lat,lon);await loadBuildings(lat,lon)}
function start(){if(!navigator.geolocation){statusEl.textContent='Brak obsługi GPS';return}if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=navigator.geolocation.watchPosition(onPos,e=>statusEl.textContent='GPS: '+e.message,{enableHighAccuracy:true,maximumAge:5000,timeout:20000})}


const settingsToggle=document.querySelector('#settingsToggle'),settingsPanel=document.querySelector('#settingsPanel'),closeSettings=document.querySelector('#closeSettings');
function setSettings(open){settingsPanel.classList.toggle('open',open);settingsToggle.setAttribute('aria-expanded',open?'true':'false')}
settingsToggle.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();setSettings(!settingsPanel.classList.contains('open'))});
closeSettings.addEventListener('click',()=>setSettings(false));
document.addEventListener('click',e=>{if(settingsPanel.classList.contains('open')&&!settingsPanel.contains(e.target)&&e.target!==settingsToggle)setSettings(false)});

refreshDaysInput.addEventListener('change',()=>{let v=Math.max(1,Math.min(365,Number(refreshDaysInput.value)||30));refreshDaysInput.value=v;localStorage.setItem('safeHuntRefreshDays',String(v));statusEl.textContent='Odświeżanie danych ustawione co '+v+' dni.'});
document.querySelector('#resetEdits').addEventListener('click',()=>{if(!manualFeatures.length&&!deletedIds.size){statusEl.textContent='Brak ręcznych zmian do przywrócenia.';return}if(!confirm('Usunąć wszystkie ręcznie dodane budynki i przywrócić wszystkie ukryte budynki?'))return;manualFeatures=[];deletedIds.clear();undoStack=[];document.querySelector('#undoEdit').disabled=true;saveEdits();redraw();statusEl.textContent='Przywrócono mapę do danych źródłowych.'});
const minPanel=document.querySelector('#minPanel');const panelBody=document.querySelector('#panelBody');function setPanelCollapsed(collapsed){panel.classList.toggle('collapsed',collapsed);panelBody.hidden=collapsed;minPanel.textContent=collapsed?'⌃':'⌄';minPanel.setAttribute('aria-label',collapsed?'Rozwiń panel':'Minimalizuj panel');localStorage.setItem('safeHuntPanelCollapsed',collapsed?'1':'0');setTimeout(()=>map.invalidateSize(),80)}minPanel.addEventListener('click',()=>setPanelCollapsed(!panel.classList.contains('collapsed')));if(localStorage.getItem('safeHuntPanelCollapsed')==='1')setPanelCollapsed(true);
document.querySelector('#start').addEventListener('click',start);document.querySelector('#refresh').addEventListener('click',()=>navigator.geolocation.getCurrentPosition(p=>loadBuildings(p.coords.latitude,p.coords.longitude,true),()=>{statusEl.textContent='Nie udało się pobrać pozycji GPS.'},{enableHighAccuracy:true}));document.querySelector('#centerMap').addEventListener('click',e=>{e.preventDefault();e.stopPropagation();fitSafety()});
function setEdit(mode){editMode=editMode===mode?null:mode;document.querySelector('#addBuilding').classList.toggle('active',editMode==='add');document.querySelector('#removeBuilding').classList.toggle('active',editMode==='remove');editHint.style.display=editMode?'block':'none';editHint.textContent=editMode==='add'?'Dotknij mapy w miejscu budynku, aby dodać go ręcznie.':'Dotknij budynku na mapie, aby ukryć go na tym urządzeniu.'}
document.querySelector('#undoEdit').addEventListener('click',e=>{e.preventDefault();e.stopPropagation();undoLast()});map.on('moveend zoomend',()=>renderSafeDistanceZone());document.querySelector('#addBuilding').addEventListener('click',e=>{e.preventDefault();e.stopPropagation();setEdit('add')});document.querySelector('#removeBuilding').addEventListener('click',e=>{e.preventDefault();e.stopPropagation();setEdit('remove')});map.on('click',e=>{if(!editMode)return;if(editMode==='add'){const nf={type:'Feature',properties:{manual:true,id:Date.now()},geometry:{type:'Point',coordinates:[e.latlng.lng,e.latlng.lat]}};manualFeatures.push(nf);pushUndo({type:'addManual',feature:nf});saveEdits();redraw();setEdit(null);statusEl.textContent='Dodano budynek ręcznie.';return}let best=null,bd=Infinity;for(const f of features){if(deletedIds.has(String(f.properties?.osmId)))continue;const r=geomNearest([e.latlng.lat,e.latlng.lng],f.geometry);if(r.distance<bd){bd=r.distance;best=f}}if(best&&bd<40){const id=String(best.properties.osmId);deletedIds.add(id);pushUndo({type:'deleteOsm',id});saveEdits();redraw();setEdit(null)}else{statusEl.textContent='Dotknij bliżej obrysu budynku (do 40 m).'}});
// NOAA-style sunrise/sunset approximation.
function sunTime(date,lat,lon,isRise){const N=Math.floor((Date.UTC(date.getFullYear(),date.getMonth(),date.getDate())-Date.UTC(date.getFullYear(),0,0))/86400000),lngHour=lon/15,t=N+((isRise?6:18)-lngHour)/24,M=.9856*t-3.289,L=(M+1.916*Math.sin(rad(M))+.020*Math.sin(rad(2*M))+282.634)%360,RA=(Math.atan(.91764*Math.tan(rad(L)))*180/Math.PI)%360;let ra=(RA+360)%360;ra+=(Math.floor(L/90)*90-Math.floor(ra/90)*90);ra/=15;const sinDec=.39782*Math.sin(rad(L)),cosDec=Math.cos(Math.asin(sinDec)),cosH=(Math.cos(rad(90.833))-sinDec*Math.sin(rad(lat)))/(cosDec*Math.cos(rad(lat)));if(cosH>1||cosH<-1)return null;let H=(isRise?360-Math.acos(cosH)*180/Math.PI:Math.acos(cosH)*180/Math.PI)/15,T=H+ra-.06571*t-6.622,UT=(T-lngHour+24)%24;return new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate())+UT*3600000)}
let solar={sunrise:null,sunset:null,night:false};function updateSolar(lat,lon){const now=new Date(),rise=sunTime(now,lat,lon,true),set=sunTime(now,lat,lon,false);solar.sunrise=rise;solar.sunset=set;const darkStart=set?new Date(set.getTime()+3600000):null,lightStart=rise?new Date(rise.getTime()+3600000):null;solar.night=!!(darkStart&&lightStart&&(now>=darkStart||now<lightStart));document.body.classList.toggle('night',solar.night);const f=d=>d?d.toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit'}):'—';document.querySelector('#daylight').innerHTML=`Wschód: <b>${f(rise)}</b> · zachód: <b>${f(set)}</b><br>Tryb mapy: <b>${solar.night?'ciemny':'jasny'}</b>`}
const game=[['Dzik','cały rok',()=>true,true],['Norka amerykańska','cały rok',()=>true,true],['Lis','1 VI – 31 III*',d=>inSeason(d,6,1,3,31),true],['Jeleń szlachetny – byki','21 VIII – koniec II',d=>inSeason(d,8,21,2,29),false],['Jeleń szlachetny – łanie','1 IX – 15 I',d=>inSeason(d,9,1,1,15),false],['Jeleń szlachetny – cielęta','1 IX – koniec II',d=>inSeason(d,9,1,2,29),false],['Daniel – byki','1 IX – koniec II',d=>inSeason(d,9,1,2,29),false],['Daniel – łanie','1 IX – 15 I',d=>inSeason(d,9,1,1,15),false],['Daniel – cielęta','1 IX – koniec II',d=>inSeason(d,9,1,2,29),false],['Sarna – kozły','11 V – 30 IX',d=>inSeason(d,5,11,9,30),false],['Sarna – kozy i koźlęta','1 X – 15 I',d=>inSeason(d,10,1,1,15),false],['Muflon – tryki','1 X – koniec II',d=>inSeason(d,10,1,2,29),false],['Muflon – owce i jagnięta','1 X – 15 I',d=>inSeason(d,10,1,1,15),false],['Borsuk','1 IX – 30 XI*',d=>inSeason(d,9,1,11,30),true],['Kuny i tchórz','1 IX – 31 III*',d=>inSeason(d,9,1,3,31),false],['Zając / dziki królik','1 XI – 31 XII**',d=>inSeason(d,11,1,12,31),false],['Bażant – kogut','1 X – koniec II',d=>inSeason(d,10,1,2,29),false],['Kuropatwa','11 IX – 21 X',d=>inSeason(d,9,11,10,21),false],['Gęś gęgawa','wg regionu – sprawdź przepisy',d=>[9,10,11,12,1].includes(d.getMonth()+1),false],['Gęsi zbożowe/białoczelne','wg regionu – sprawdź przepisy',d=>[9,10,11,12,1].includes(d.getMonth()+1),false]];function md(d){return(d.getMonth()+1)*100+d.getDate()}function inSeason(d,sm,sd,em,ed){const x=md(d),s=sm*100+sd,e=em*100+ed;return s<=e?x>=s&&x<=e:x>=s||x<=e}function updateGameInfo(){const now=new Date(),night=solar.night,list=document.querySelector('#gameList');const active=game.filter(x=>x[2](now)&&(!night||x[3]));list.innerHTML=active.length?active.map(x=>`<div class="gameItem"><b>${x[0]}</b><small>${x[1]}${night&&x[3]?' · dopuszczalne polowanie nocne przy spełnieniu warunków':''}</small></div>`).join(''):'<div class="gameItem">Brak pozycji w uproszczonym kalendarzu dla tej chwili.</div>';if(night)list.insertAdjacentHTML('afterbegin','<div class="gameItem"><b>🌙 Pora nocna</b><small>Lista ograniczona do gatunków uwzględnionych w aplikacji jako dopuszczone do polowania nocnego. Sprawdź wymagane wyposażenie i wyjątki.</small></div>')}
document.querySelector('#gameToggle').onclick=()=>document.querySelector('#gamePanel').classList.add('open');document.querySelector('#closeGame').onclick=()=>document.querySelector('#gamePanel').classList.remove('open');loadEdits();redraw();updateGameInfo();setInterval(()=>{if(lastPos)updateSolar(...lastPos);updateGameInfo()},60000);if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(r=>r.update()).catch(()=>{})}
