const map=L.map('map',{zoomControl:false}).setView([51.76,19.46],11);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
let me,accuracyCircle,safetyLine=null,buildingsLayer=L.geoJSON(null,{style:{weight:1,fillOpacity:.22}}).addTo(map),features=[],lastFetch=null,watchId=null,lastPos=null,lastBest=Infinity,lastNearestPoint=null;
const distEl=document.querySelector('#distance'),statusEl=document.querySelector('#status'),accEl=document.querySelector('#accuracy'),panel=document.querySelector('#panel'),safeInput=document.querySelector('#safeDistance');
const saved=localStorage.getItem('safeDistance');if(saved)safeInput.value=saved;safeInput.onchange=()=>{let v=Math.max(1,Math.min(5000,Number(safeInput.value)||150));safeInput.value=v;localStorage.setItem('safeDistance',v);applyWarning(lastBest)};
function rad(x){return x*Math.PI/180} function hav(a,b){const R=6371000,dLat=rad(b[0]-a[0]),dLon=rad(b[1]-a[1]),x=Math.sin(dLat/2)**2+Math.cos(rad(a[0]))*Math.cos(rad(b[0]))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function segNearest(p,a,b){const lat0=rad(p[0]),mx=111320*Math.cos(lat0),my=110540;let px=p[1]*mx,py=p[0]*my,ax=a[1]*mx,ay=a[0]*my,bx=b[1]*mx,by=b[0]*my,dx=bx-ax,dy=by-ay,t=((px-ax)*dx+(py-ay)*dy)/(dx*dx+dy*dy||1);t=Math.max(0,Math.min(1,t));const qx=ax+t*dx,qy=ay+t*dy;return{distance:Math.hypot(px-qx,py-qy),point:[qy/my,qx/mx]}}
function ringNearest(p,ring){let best={distance:Infinity,point:null};for(let i=1;i<ring.length;i++){const r=segNearest(p,[ring[i-1][1],ring[i-1][0]],[ring[i][1],ring[i][0]]);if(r.distance<best.distance)best=r}return best}
function geomNearest(p,g){let best={distance:Infinity,point:null};const rings=g.type==='Polygon'?g.coordinates:g.type==='MultiPolygon'?g.coordinates.flat():[];for(const ring of rings){const r=ringNearest(p,ring);if(r.distance<best.distance)best=r}return best}
function updateSafetyLine(p,best,nearest){const limit=Number(safeInput.value||150),show=Number.isFinite(best)&&best<limit&&nearest;if(show){if(!safetyLine)safetyLine=L.polyline([p,nearest],{weight:4,dashArray:'10 8',opacity:.9,interactive:false}).addTo(map);else safetyLine.setLatLngs([p,nearest]);}else if(safetyLine){map.removeLayer(safetyLine);safetyLine=null;}}
function applyWarning(best){lastBest=best;panel.classList.toggle('warn',Number.isFinite(best)&&best<Number(safeInput.value||150));if(lastPos)updateSafetyLine(lastPos,lastBest,lastNearestPoint)}function updateNearest(lat,lon){if(!features.length){distEl.textContent='— m';lastNearestPoint=null;updateSafetyLine([lat,lon],Infinity,null);return}let best=Infinity,nearest=null;for(const f of features){const r=geomNearest([lat,lon],f.geometry);if(r.distance<best){best=r.distance;nearest=r.point}}lastNearestPoint=nearest;distEl.textContent=Math.round(best)+' m';statusEl.textContent=best<Number(safeInput.value)?'UWAGA — poniżej ustawionej odległości':'Odległość do najbliższego obrysu budynku';applyWarning(best);updateSafetyLine([lat,lon],best,nearest)}
const overpassServers=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter','https://overpass.private.coffee/api/interpreter'];
function cacheBuildings(lat,lon){try{localStorage.setItem('safeHuntBuildings',JSON.stringify({lat,lon,at:Date.now(),features}))}catch(e){}}
function restoreBuildings(lat,lon){try{const c=JSON.parse(localStorage.getItem('safeHuntBuildings')||'null');if(c&&Array.isArray(c.features)&&c.features.length&&hav([lat,lon],[c.lat,c.lon])<1200){features=c.features;lastFetch=[c.lat,c.lon];buildingsLayer.clearLayers();buildingsLayer.addData({type:'FeatureCollection',features});updateNearest(lat,lon);statusEl.textContent='Używam zapisanych budynków — odświeżam dane…';return true}}catch(e){}return false}
async function fetchWithTimeout(url,q,ms=12000){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),ms);try{const body='data='+encodeURIComponent(q);const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body,signal:ctrl.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(timer)}}
async function loadBuildings(lat,lon){const hadCache=restoreBuildings(lat,lon);statusEl.textContent=hadCache?'Używam zapisanych budynków — odświeżam dane…':'Pobieram budynki…';const q=`[out:json][timeout:20];way["building"](around:1500,${lat},${lon});out geom;`;let lastError='';for(let i=0;i<overpassServers.length;i++){try{statusEl.textContent=(hadCache?'Odświeżam':'Pobieram')+` budynki… serwer ${i+1}/${overpassServers.length}`;const data=await fetchWithTimeout(overpassServers[i],q);const fresh=data.elements.filter(e=>e.type==='way'&&e.geometry?.length>2).map(e=>({type:'Feature',properties:{osmId:e.id},geometry:{type:'Polygon',coordinates:[e.geometry.map(x=>[x.lon,x.lat])]}}));if(!fresh.length)throw new Error('Brak budynków w odpowiedzi');features=fresh;buildingsLayer.clearLayers();buildingsLayer.addData({type:'FeatureCollection',features});lastFetch=[lat,lon];cacheBuildings(lat,lon);updateNearest(lat,lon);return}catch(e){lastError=e.name==='AbortError'?'przekroczony czas odpowiedzi':e.message}}
if(hadCache){updateNearest(lat,lon);statusEl.textContent='Dane offline — nie udało się odświeżyć budynków';}else{statusEl.textContent='Nie udało się pobrać budynków ('+lastError+'). Spróbuj „Odśwież budynki”.'}}
const hunterIcon=L.divIcon({className:'hunter-icon',html:'<div class="hunter-badge">🧑‍🌾</div>',iconSize:[48,48],iconAnchor:[24,24]});
function onPos(pos){const {latitude:lat,longitude:lon,accuracy}=pos.coords;lastPos=[lat,lon];accEl.textContent='Dokładność GPS: ±'+Math.round(accuracy)+' m';if(!me){me=L.marker([lat,lon],{icon:hunterIcon}).addTo(map);accuracyCircle=L.circle([lat,lon],{radius:accuracy,weight:1,fillOpacity:.06}).addTo(map);map.setView([lat,lon],17)}else{me.setLatLng([lat,lon]);accuracyCircle.setLatLng([lat,lon]).setRadius(accuracy)}updateSolar(lat,lon);updateGameInfo();if(!lastFetch||hav([lat,lon],lastFetch)>500)loadBuildings(lat,lon);else updateNearest(lat,lon)}
function start(){if(!navigator.geolocation){statusEl.textContent='Brak obsługi GPS';return}if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=navigator.geolocation.watchPosition(onPos,e=>statusEl.textContent='GPS: '+e.message,{enableHighAccuracy:true,maximumAge:2000,timeout:15000})}
document.querySelector('#start').onclick=start;document.querySelector('#refresh').onclick=()=>navigator.geolocation.getCurrentPosition(p=>loadBuildings(p.coords.latitude,p.coords.longitude),()=>{},{enableHighAccuracy:true});
// NOAA-style sunrise/sunset approximation; returned Date is UTC converted automatically by browser.
function sunTime(date,lat,lon,isRise){const N=Math.floor((Date.UTC(date.getFullYear(),date.getMonth(),date.getDate())-Date.UTC(date.getFullYear(),0,0))/86400000),lngHour=lon/15,t=N+((isRise?6:18)-lngHour)/24,M=.9856*t-3.289,L=(M+1.916*Math.sin(rad(M))+.020*Math.sin(rad(2*M))+282.634)%360,RA=(Math.atan(.91764*Math.tan(rad(L)))*180/Math.PI)%360;let ra=(RA+360)%360;ra+=(Math.floor(L/90)*90-Math.floor(ra/90)*90);ra/=15;const sinDec=.39782*Math.sin(rad(L)),cosDec=Math.cos(Math.asin(sinDec)),cosH=(Math.cos(rad(90.833))-sinDec*Math.sin(rad(lat)))/(cosDec*Math.cos(rad(lat)));if(cosH>1||cosH<-1)return null;let H=(isRise?360-Math.acos(cosH)*180/Math.PI:Math.acos(cosH)*180/Math.PI)/15,T=H+ra-.06571*t-6.622,UT=(T-lngHour+24)%24;return new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate(),0,0,0)+UT*3600000)}
let solar={sunrise:null,sunset:null,night:false};function updateSolar(lat,lon){const now=new Date(),rise=sunTime(now,lat,lon,true),set=sunTime(now,lat,lon,false);solar.sunrise=rise;solar.sunset=set;const darkStart=set?new Date(set.getTime()+3600000):null,lightStart=rise?new Date(rise.getTime()+3600000):null;solar.night=!!(darkStart&&lightStart&&(now>=darkStart||now<lightStart));document.body.classList.toggle('night',solar.night);const f=d=>d?d.toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit'}):'—';document.querySelector('#daylight').innerHTML=`Wschód: <b>${f(rise)}</b> · zachód: <b>${f(set)}</b><br>Tryb mapy: <b>${solar.night?'ciemny':'jasny'}</b>`}
// Uproszczony kalendarz ogólnopolski. Wyjątki regionalne/obwodowe są opisane przy pozycji.
const game=[
['Dzik','cały rok',()=>true,true],['Norka amerykańska','cały rok',()=>true,true],['Lis','1 VI – 31 III*',d=>inSeason(d,6,1,3,31),true],['Jeleń szlachetny – byki','21 VIII – koniec II',d=>inSeason(d,8,21,2,29),false],['Jeleń szlachetny – łanie','1 IX – 15 I',d=>inSeason(d,9,1,1,15),false],['Jeleń szlachetny – cielęta','1 IX – koniec II',d=>inSeason(d,9,1,2,29),false],['Daniel – byki','1 IX – koniec II',d=>inSeason(d,9,1,2,29),false],['Daniel – łanie','1 IX – 15 I',d=>inSeason(d,9,1,1,15),false],['Daniel – cielęta','1 IX – koniec II',d=>inSeason(d,9,1,2,29),false],['Sarna – kozły','11 V – 30 IX',d=>inSeason(d,5,11,9,30),false],['Sarna – kozy i koźlęta','1 X – 15 I',d=>inSeason(d,10,1,1,15),false],['Muflon – tryki','1 X – koniec II',d=>inSeason(d,10,1,2,29),false],['Muflon – owce i jagnięta','1 X – 15 I',d=>inSeason(d,10,1,1,15),false],['Borsuk','1 IX – 30 XI*',d=>inSeason(d,9,1,11,30),true],['Kuny i tchórz','1 IX – 31 III*',d=>inSeason(d,9,1,3,31),false],['Zając / dziki królik','1 XI – 31 XII**',d=>inSeason(d,11,1,12,31),false],['Bażant – kogut','1 X – koniec II',d=>inSeason(d,10,1,2,29),false],['Kuropatwa','11 IX – 21 X',d=>inSeason(d,9,11,10,21),false],['Gęś gęgawa','wg regionu – sprawdź przepisy',d=>[9,10,11,12,1].includes(d.getMonth()+1),false],['Gęsi zbożowe/białoczelne','wg regionu – sprawdź przepisy',d=>[9,10,11,12,1].includes(d.getMonth()+1),false]
];function md(d){return (d.getMonth()+1)*100+d.getDate()}function inSeason(d,sm,sd,em,ed){const x=md(d),s=sm*100+sd,e=em*100+ed;return s<=e?x>=s&&x<=e:x>=s||x<=e}
function updateGameInfo(){const now=new Date(),night=solar.night,list=document.querySelector('#gameList');const active=game.filter(x=>x[2](now)&&(!night||x[3]));list.innerHTML=active.length?active.map(x=>`<div class="gameItem"><b>${x[0]}</b><small>${x[1]}${night&&x[3]?' · dopuszczalne polowanie nocne przy spełnieniu warunków':''}</small></div>`).join(''):'<div class="gameItem">Brak pozycji w uproszczonym kalendarzu dla tej chwili.</div>';if(night)list.insertAdjacentHTML('afterbegin','<div class="gameItem"><b>🌙 Pora nocna</b><small>Lista ograniczona do gatunków uwzględnionych w aplikacji jako dopuszczone do polowania nocnego. Sprawdź wymagane wyposażenie i wyjątki.</small></div>')}
document.querySelector('#gameToggle').onclick=()=>document.querySelector('#gamePanel').classList.add('open');document.querySelector('#closeGame').onclick=()=>document.querySelector('#gamePanel').classList.remove('open');updateGameInfo();setInterval(()=>{if(lastPos)updateSolar(...lastPos);updateGameInfo()},60000);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
