const map=L.map('map').setView([51.76,19.46],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
let me,accuracyCircle,buildingsLayer=L.geoJSON(null,{style:{weight:1,fillOpacity:.25}}).addTo(map),features=[],lastFetch=null,watchId=null;
const distEl=document.querySelector('#distance'), statusEl=document.querySelector('#status'), accEl=document.querySelector('#accuracy'), panel=document.querySelector('#panel');
function rad(x){return x*Math.PI/180} function hav(a,b){const R=6371000,dLat=rad(b[0]-a[0]),dLon=rad(b[1]-a[1]),x=Math.sin(dLat/2)**2+Math.cos(rad(a[0]))*Math.cos(rad(b[0]))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function segDist(p,a,b){const lat0=rad(p[0]),mx=111320*Math.cos(lat0),my=110540;let px=p[1]*mx,py=p[0]*my,ax=a[1]*mx,ay=a[0]*my,bx=b[1]*mx,by=b[0]*my,dx=bx-ax,dy=by-ay,t=((px-ax)*dx+(py-ay)*dy)/(dx*dx+dy*dy||1);t=Math.max(0,Math.min(1,t));return Math.hypot(px-(ax+t*dx),py-(ay+t*dy))}
function ringDist(p,ring){let d=Infinity;for(let i=1;i<ring.length;i++)d=Math.min(d,segDist(p,[ring[i-1][1],ring[i-1][0]],[ring[i][1],ring[i][0]]));return d}
function geomDist(p,g){if(g.type==='Polygon')return Math.min(...g.coordinates.map(r=>ringDist(p,r)));if(g.type==='MultiPolygon')return Math.min(...g.coordinates.flatMap(poly=>poly.map(r=>ringDist(p,r))));return Infinity}
function updateNearest(lat,lon){if(!features.length){distEl.textContent='— m';return}let best=Infinity;for(const f of features)best=Math.min(best,geomDist([lat,lon],f.geometry));distEl.textContent=Math.round(best)+' m';statusEl.textContent='Odległość do najbliższego obrysu budynku';panel.classList.toggle('warn',best<150)}
async function loadBuildings(lat,lon){statusEl.textContent='Pobieram budynki…';const q=`[out:json][timeout:25];(way["building"](around:1500,${lat},${lon});relation["building"](around:1500,${lat},${lon}););out geom;`;try{const r=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:q});if(!r.ok)throw Error();const data=await r.json();features=data.elements.filter(e=>e.geometry?.length>2).map(e=>({type:'Feature',properties:{},geometry:{type:'Polygon',coordinates:[e.geometry.map(x=>[x.lon,x.lat])]}}));buildingsLayer.clearLayers();buildingsLayer.addData({type:'FeatureCollection',features});lastFetch=[lat,lon];updateNearest(lat,lon)}catch(e){statusEl.textContent='Nie udało się pobrać budynków';}}
function onPos(pos){const {latitude:lat,longitude:lon,accuracy}=pos.coords;accEl.textContent='Dokładność GPS: ±'+Math.round(accuracy)+' m';if(!me){me=L.circleMarker([lat,lon],{radius:8,weight:3,fillOpacity:1}).addTo(map);accuracyCircle=L.circle([lat,lon],{radius:accuracy,weight:1,fillOpacity:.06}).addTo(map);map.setView([lat,lon],17)}else{me.setLatLng([lat,lon]);accuracyCircle.setLatLng([lat,lon]).setRadius(accuracy)}if(!lastFetch||hav([lat,lon],lastFetch)>500)loadBuildings(lat,lon);else updateNearest(lat,lon)}
function start(){if(!navigator.geolocation){statusEl.textContent='Brak obsługi GPS';return}if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=navigator.geolocation.watchPosition(onPos,e=>statusEl.textContent='GPS: '+e.message,{enableHighAccuracy:true,maximumAge:2000,timeout:15000})}
document.querySelector('#start').onclick=start;document.querySelector('#refresh').onclick=()=>navigator.geolocation.getCurrentPosition(p=>loadBuildings(p.coords.latitude,p.coords.longitude),()=>{}, {enableHighAccuracy:true});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
